"use client";
import { useEffect, useState, type ReactNode } from "react";
import { copy, disciplines, goals, newModule, projectTalent, talentSchema, type Copy, type Talent, talentBrand } from "@/lib/talent/model";
import { talentLabels } from "@/lib/talent/labels";
import { TalentView } from "./view";
import { saveTalent } from "@/app/app/profiles/[profileId]/talent/actions";

type Locale = "en" | "es";
const inputClass = "w-full rounded-lg border border-line-strong bg-bg px-3 py-2 text-sm text-ink focus:outline-none focus:ring-2 focus:ring-gold";
function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (v: string) => void; type?: string }) {
  return <label className="block text-sm space-y-1"><span className="text-ink-soft">{label}</span><input type={type} className={inputClass} value={value} onChange={e => onChange(e.target.value)} /></label>;
}
function LocalizedField({ label, value, onChange, long = false }: { label: string; value: Copy; onChange: (v: Copy) => void; long?: boolean }) {
  return <fieldset className="grid sm:grid-cols-2 gap-2"><legend className="text-sm mb-1 text-ink-soft">{label}</legend>{(["en", "es"] as const).map(lang => <label key={lang} className="block"><span className="block text-xs text-ink-soft mb-1">{lang === "en" ? "English" : "Español"}</span>{long ? <textarea className={inputClass} rows={3} lang={lang} value={value[lang]} onChange={e => onChange({ ...value, [lang]: e.target.value })} /> : <input className={inputClass} lang={lang} value={value[lang]} onChange={e => onChange({ ...value, [lang]: e.target.value })} />}</label>)}</fieldset>;
}
function Check({ label, value, onChange }: { label: string; value: boolean; onChange: (v: boolean) => void }) {
  return <label className="inline-flex items-center gap-2 text-sm py-1"><input type="checkbox" checked={value} onChange={e => onChange(e.target.checked)} className="accent-[hsl(var(--gold))]" />{label}</label>;
}
function Select({ label, value, options, onChange }: { label: string; value: string; options: { value: string; label: string }[]; onChange: (v: string) => void }) {
  return <label className="block text-sm space-y-1"><span className="text-ink-soft">{label}</span><select className={inputClass} value={value} onChange={e => onChange(e.target.value)}>{options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;
}
function Panel({ title, children }: { title: string; children: ReactNode }) {
  return <details className="border border-line rounded-2xl bg-bg-raised" open><summary className="cursor-pointer p-5 font-display text-xl">{title}</summary><div className="px-5 pb-5 space-y-4">{children}</div></details>;
}
function Collection<T extends { id: string; visible: boolean }>({ title, rows, onChange, create, children, locale }: { title: string; rows: T[]; onChange: (rows: T[]) => void; create: () => T; children: (row: T, patch: (v: Partial<T>) => void) => ReactNode; locale: Locale }) {
  const t = talentLabels[locale];
  const move = (i: number, delta: number) => { const next = [...rows]; [next[i], next[i + delta]] = [next[i + delta], next[i]]; onChange(next); };
  return <Panel title={title}>{rows.map((r, i) => <fieldset key={r.id} className="border border-line rounded-xl p-4 space-y-3"><legend className="px-2 text-sm">{title} {i + 1}</legend>{children(r, v => onChange(rows.map(x => x.id === r.id ? { ...x, ...v } : x)))}<div className="flex flex-wrap items-center justify-between gap-3"><Check label={t.visible} value={r.visible} onChange={visible => onChange(rows.map(x => x.id === r.id ? { ...x, visible } : x))} /><div className="flex gap-3 text-xs"><button type="button" disabled={i === 0} onClick={() => move(i, -1)} className="disabled:opacity-30 underline">{t.up}</button><button type="button" disabled={i === rows.length - 1} onClick={() => move(i, 1)} className="disabled:opacity-30 underline">{t.down}</button><button type="button" onClick={() => onChange(rows.filter(x => x.id !== r.id))} className="text-err underline">{t.remove}</button></div></div></fieldset>)}<button type="button" onClick={() => onChange([...rows, create()])} className="rounded-full border border-line-strong px-4 py-2 text-sm">+ {t.add}</button></Panel>;
}
const rowId = () => crypto.randomUUID();
export function TalentEditor({ profileId, username, initial, revision: initialRevision, published: initialPublished, locale }: { profileId: string; username: string; initial: Talent; revision: number; published: boolean; locale: Locale }) {
  const [p, setP] = useState(initial); const [revision, setRevision] = useState(initialRevision); const [published, setPublished] = useState(initialPublished);
  const [dirty, setDirty] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [errors, setErrors] = useState<string[]>([]); const [preview, setPreview] = useState(false);
  const t = talentLabels[locale];
  const patch = (v: Partial<Talent>) => { setP(prev => ({ ...prev, ...v })); setDirty(true); setMessage(""); setErrors([]); };
  useEffect(() => { const handler = (e: BeforeUnloadEvent) => { if (dirty) { e.preventDefault(); e.returnValue = ""; } }; window.addEventListener("beforeunload", handler); return () => window.removeEventListener("beforeunload", handler); }, [dirty]);
  const options = (keys: readonly string[]) => keys.map(value => ({ value, label: t[value as keyof typeof t] || value }));
  const disciplineOptions = [{ value: "", label: t.general }, ...options(p.disciplines)];
  async function save(operation: "draft" | "publish" | "unpublish") {
    if (busy) return;
    const parsed = talentSchema.safeParse(p);
    if (!parsed.success) { setErrors(parsed.error.issues.map(i => i.path.join("."))); setMessage(t.invalid); return; }
    setBusy(true); setMessage("");
    try {
      const result = await saveTalent(profileId, parsed.data, revision, operation);
      if (result.ok) { setRevision(result.revision); setDirty(false); if (operation !== "draft") setPublished(operation === "publish"); setMessage(operation === "draft" ? t.saved : operation === "publish" ? t.live : t.unpublished); }
      else { setMessage(result.code === "conflict" ? t.conflict : result.code === "invalid" ? t.invalid : t.error); setErrors(result.fields || []); }
    } catch { setMessage(t.error); } finally { setBusy(false); }
  }
  const parsedPreview = talentSchema.safeParse(p);
  const primaryContacts = p.contacts.filter(c => c.visible && c.goals.includes(p.primaryGoal) && (!p.youth || c.role !== "talent"));
  return <div lang={locale} className="space-y-6">
    <a href={`/app/profiles/${profileId}?lang=${locale}`} className="text-sm underline">← {t.back}</a>
    <div><p className="text-xs uppercase tracking-widest text-gold">SnapLink SOLO</p><h1 className="font-display text-4xl mt-2">{talentBrand(p.primaryDiscipline) ? `${talentBrand(p.primaryDiscipline)} Studio` : t.editor}</h1><p className="text-sm text-ink-soft mt-3">{t.locales}</p><p className="text-xs text-ink-soft mt-2">{published ? t.live : t.unpublished}{dirty ? ` · ${t.pending}` : ""}</p></div>
    <div className="flex flex-wrap gap-3"><button type="button" className="border border-line-strong rounded-full px-4 py-2 text-sm" onClick={() => { if (!parsedPreview.success) { setMessage(t.invalid); setErrors(parsedPreview.error.issues.map(i => i.path.join("."))); } else setPreview(!preview); }}>{preview ? t.edit : t.preview}</button>{published && <a className="text-sm underline self-center" href={`/u/${username}?lang=${locale}`} target="_blank" rel="noopener noreferrer">{t.view} ↗</a>}</div>
    <p className="text-sm text-ink-soft">{t.publicFiles}</p>
    {preview && parsedPreview.success ? <><p className="text-sm text-ink-soft">{t.savedPreview}</p><TalentView talent={projectTalent(parsedPreview.data)} locale={locale} /></> : <fieldset disabled={busy} className="space-y-5 disabled:opacity-60">
      <Panel title={t.identity}>
        <Field label={t.name} value={p.displayName} onChange={displayName => patch({ displayName })} />
        <LocalizedField label={t.headline} value={p.headline} onChange={headline => patch({ headline })} />
        <LocalizedField label={t.bio} value={p.bio} onChange={bio => patch({ bio })} long />
        <Field label={t.portrait} value={p.portrait} onChange={portrait => patch({ portrait })} type="url" /><Field label={t.cover} value={p.cover} onChange={cover => patch({ cover })} type="url" />
        <Field label={t.location} value={p.location} onChange={location => patch({ location })} /><Check label={t.showLocation} value={p.showLocation} onChange={showLocation => patch({ showLocation })} />
        <div><Check label={t.youth} value={p.youth} onChange={youth => patch({ youth, primaryContactId: "" })} /></div>
      </Panel>
      <Panel title={t.disciplines}><div className="flex flex-wrap gap-4">{disciplines.map(d => <Check key={d} label={t[d]} value={p.disciplines.includes(d)} onChange={enabled => {
        const selected = enabled ? [...p.disciplines, d] : p.disciplines.filter(x => x !== d); if (!selected.length) return;
        patch({ disciplines: selected, primaryDiscipline: selected.includes(p.primaryDiscipline) ? p.primaryDiscipline : selected[0] });
      }} />)}</div><Select label={t.primary} value={p.primaryDiscipline} options={options(p.disciplines)} onChange={v => patch({ primaryDiscipline: v as Talent["primaryDiscipline"] })} />
      {p.disciplines.map(d => { const m = p.modules[d] || newModule()!; const edit = (change: Partial<typeof m>) => patch({ modules: { ...p.modules, [d]: { ...m, ...change } } }); return <details key={d} className="border-t border-line pt-3"><summary className="cursor-pointer font-medium">{t[d]} · {t.module}</summary><div className="space-y-3 pt-4"><Check label={t.modulePublic} value={m.visible} onChange={visible => edit({ visible })} />{(["affiliation", "skills", "training", ...(d === "actor" ? ["languages", "representation"] : []), ...(d === "dancer" ? ["styles"] : [])] as const).map(k => <LocalizedField key={k} label={t[k as keyof typeof t]} value={m[k as "affiliation"]} onChange={v => edit({ [k]: v })} />)}{(d === "athlete" || d === "cheer") && <><Field label={t.sport} value={m.sport} onChange={sport => edit({ sport })} /><Field label={t.position} value={m.position} onChange={position => edit({ position })} /></>}</div></details>; })}</Panel>
      <Panel title={t.goals}><div className="flex flex-wrap gap-4">{goals.map(g => <Check key={g} label={t[g]} value={p.goals.includes(g)} onChange={enabled => { const selected = enabled ? [...p.goals, g] : p.goals.filter(x => x !== g); if (!selected.length) return; patch({ goals: selected, primaryGoal: selected.includes(p.primaryGoal) ? p.primaryGoal : selected[0], primaryContactId: "" }); }} />)}</div><Select label={t.primary} value={p.primaryGoal} options={options(p.goals)} onChange={v => patch({ primaryGoal: v as Talent["primaryGoal"], primaryContactId: "" })} /></Panel>
      <Collection title={t.portfolio} rows={p.media} locale={locale} onChange={media => patch({ media, featuredReelId: media.some(m => m.id === p.featuredReelId && m.kind === "video") ? p.featuredReelId : "" })} create={() => ({ id: rowId(), visible: false, kind: "image" as const, url: "", poster: "", title: copy(), caption: copy(), alt: copy() })}>{(m, edit) => <><Select label={t.portfolio} value={m.kind} options={options(["image", "video"])} onChange={kind => edit({ kind: kind as "image" | "video" })} /><Field label={t.url} value={m.url} onChange={url => edit({ url })} type="url" /><LocalizedField label={t.title} value={m.title} onChange={title => edit({ title })} /><LocalizedField label={t.caption} value={m.caption} onChange={caption => edit({ caption })} /><LocalizedField label={t.alt} value={m.alt} onChange={alt => edit({ alt })} />{m.kind === "video" && <Field label={t.poster} value={m.poster} onChange={poster => edit({ poster })} type="url" />}</>}</Collection>
      <Select label={t.featured} value={p.featuredReelId} options={[{ value: "", label: t.none }, ...p.media.filter(m => m.kind === "video").map(m => ({ value: m.id, label: m.title[locale] || m.title.en || m.url }))]} onChange={featuredReelId => patch({ featuredReelId })} />
      <Collection title={t.facts} rows={p.facts} locale={locale} onChange={facts => patch({ facts })} create={() => ({ id: rowId(), visible: false, key: "", label: copy(), value: { type: "text" as const, value: copy() }, observedAt: "" })}>{(f, edit) => <><Select label={t.disciplines} value={f.discipline || ""} options={disciplineOptions} onChange={d => edit({ discipline: d ? d as Talent["primaryDiscipline"] : undefined })} /><Field label={t.key} value={f.key} onChange={key => edit({ key })} /><LocalizedField label={t.title} value={f.label} onChange={label => edit({ label })} /><Select label={t.value} value={f.value.type} options={options(["text", "number", "date"])} onChange={type => edit({ value: type === "text" ? { type, value: copy() } : type === "number" ? { type, value: 0, unit: "" } : { type: "date", value: "" } })} />{f.value.type === "text" ? <LocalizedField label={t.value} value={f.value.value} onChange={value => edit({ value: { type: "text", value } })} /> : f.value.type === "number" ? <><Field label={t.value} type="number" value={String(f.value.value)} onChange={value => edit({ value: { type: "number", value: Number(value), unit: f.value.type === "number" ? f.value.unit : "" } })} /><Field label={t.unit} value={f.value.unit} onChange={unit => edit({ value: { type: "number", value: f.value.type === "number" ? f.value.value : 0, unit } })} /></> : <Field label={t.value} type="date" value={f.value.value} onChange={value => edit({ value: { type: "date", value } })} />}<Field label={t.observed} type="date" value={f.observedAt} onChange={observedAt => edit({ observedAt })} /></>}</Collection>
      <Collection title={t.credits} rows={p.credits} locale={locale} onChange={credits => patch({ credits })} create={() => ({ id: rowId(), visible: false, title: copy(), role: copy(), organization: "", date: "", evidenceUrl: "" })}>{(c, edit) => <><Select label={t.disciplines} value={c.discipline || ""} options={disciplineOptions} onChange={d => edit({ discipline: d ? d as Talent["primaryDiscipline"] : undefined })} /><LocalizedField label={t.title} value={c.title} onChange={title => edit({ title })} /><LocalizedField label={t.role} value={c.role} onChange={role => edit({ role })} /><Field label={t.organization} value={c.organization} onChange={organization => edit({ organization })} /><Field label={t.date} value={c.date} onChange={date => edit({ date })} /><Field label={t.evidenceUrl} value={c.evidenceUrl} onChange={evidenceUrl => edit({ evidenceUrl })} /></>}</Collection>
      <Collection title={t.achievements} rows={p.achievements} locale={locale} onChange={achievements => patch({ achievements })} create={() => ({ id: rowId(), visible: false, title: copy(), issuer: "", date: "", evidenceUrl: "" })}>{(a, edit) => <><LocalizedField label={t.title} value={a.title} onChange={title => edit({ title })} /><Field label={t.issuer} value={a.issuer} onChange={issuer => edit({ issuer })} /><Field label={t.date} value={a.date} onChange={date => edit({ date })} /><Field label={t.evidenceUrl} value={a.evidenceUrl} onChange={evidenceUrl => edit({ evidenceUrl })} /></>}</Collection>
      <Collection title={t.documents} rows={p.documents} locale={locale} onChange={documents => patch({ documents })} create={() => ({ id: rowId(), visible: false, kind: "resume" as const, title: copy(), url: "", published: false })}>{(d, edit) => <><Select label={t.documents} value={d.kind} options={options(["resume", "talent-sheet"])} onChange={kind => edit({ kind: kind as "resume" | "talent-sheet" })} /><LocalizedField label={t.title} value={d.title} onChange={title => edit({ title })} /><Field label={t.url} value={d.url} onChange={url => edit({ url })} type="url" /><Check label={t.publishedDocument} value={d.published} onChange={published => edit({ published })} /></>}</Collection>
      <Collection title={t.contact} rows={p.contacts} locale={locale} onChange={contacts => patch({ contacts, primaryContactId: contacts.some(c => c.id === p.primaryContactId && c.visible && c.goals.includes(p.primaryGoal) && (!p.youth || c.role !== "talent")) ? p.primaryContactId : "" })} create={() => ({ id: rowId(), visible: false, role: p.youth ? "guardian" as const : "talent" as const, label: copy(), destination: "", goals: [p.primaryGoal] })}>{(c, edit) => <><Select label={t.recipient} value={c.role} options={[{ value: "talent", label: t.talentRole }, ...options(["coach", "guardian", "agent", "manager"])]} onChange={role => edit({ role: role as typeof c.role })} /><LocalizedField label={t.title} value={c.label} onChange={label => edit({ label })} /><Field label={t.destination} value={c.destination} onChange={destination => edit({ destination })} /><div className="flex flex-wrap gap-3">{goals.map(g => <Check key={g} label={t[g]} value={c.goals.includes(g)} onChange={yes => edit({ goals: yes ? [...c.goals, g] : c.goals.filter(x => x !== g) })} />)}</div></>}</Collection>
      <Select label={`${t.primary} · ${t.contact}`} value={p.primaryContactId} options={[{ value: "", label: t.none }, ...primaryContacts.map(c => ({ value: c.id, label: c.label[locale] || c.label.en || c.destination }))]} onChange={primaryContactId => patch({ primaryContactId })} />{!p.primaryContactId && <p className="text-sm text-ink-soft">{t.emptyContact}</p>}
      <Collection title={locale === "es" ? "Enlaces" : "Links"} rows={p.links} locale={locale} onChange={links => patch({ links })} create={() => ({ id: rowId(), visible: false, label: copy(), url: "" })}>{(l, edit) => <><LocalizedField label={t.title} value={l.label} onChange={label => edit({ label })} /><Field label={t.url} value={l.url} onChange={url => edit({ url })} type="url" /></>}</Collection>
      <Panel title={t.appearance}><Select label={t.appearance} value={p.presentation.theme} options={options(["ivory", "obsidian", "signature_gold"])} onChange={theme => patch({ presentation: { ...p.presentation, theme: theme as Talent["presentation"]["theme"] } })} /><h3 className="font-medium">{t.sections}</h3>{p.presentation.sections.map((s, i) => <div key={s.id} className="flex justify-between gap-3 border-b border-line py-2"><Check label={t[s.id]} value={s.visible} onChange={visible => patch({ presentation: { ...p.presentation, sections: p.presentation.sections.map(x => x.id === s.id ? { ...x, visible } : x) } })} /><div className="flex gap-3 text-xs">{[-1, 1].map(delta => <button key={delta} disabled={i + delta < 0 || i + delta >= p.presentation.sections.length} type="button" className="underline disabled:opacity-30" onClick={() => { const sections = [...p.presentation.sections]; [sections[i], sections[i + delta]] = [sections[i + delta], sections[i]]; patch({ presentation: { ...p.presentation, sections } }); }}>{delta === -1 ? t.up : t.down}</button>)}</div></div>)}</Panel>
    </fieldset>}
    <div className="sticky bottom-16 sm:bottom-0 bg-bg/95 backdrop-blur border border-line rounded-2xl p-4 space-y-3 z-20"><p role="status" aria-live="polite" className="text-sm">{busy ? t.saving : message || (dirty ? t.pending : published ? t.live : t.unpublished)}</p>{errors.length > 0 && <ul role="alert" className="text-xs text-err list-disc pl-4">{errors.map((e, i) => <li key={`${e}-${i}`}>{e}</li>)}</ul>}<div className="flex flex-wrap gap-2"><button disabled={busy} onClick={() => save("draft")} className="rounded-full border border-line-strong px-4 py-2 text-sm disabled:opacity-40">{t.draft}</button><button disabled={busy} onClick={() => save("publish")} className="rounded-full bg-ink text-bg px-5 py-2 text-sm disabled:opacity-40">{t.publish}</button>{published && <button disabled={busy} onClick={() => save("unpublish")} className="text-sm underline px-3 disabled:opacity-40">{t.unpublish}</button>}</div></div>
  </div>;
}
