import type { ReactNode } from "react";
import { projectTalent, talentBrand, translate, type Talent } from "@/lib/talent/model";
import { talentLabels } from "@/lib/talent/labels";
import { TalentMedia } from "./media";

/** Receives only projected data at public entry points; projects again for owner previews.
 *  `compact` renders mobile layout regardless of viewport (homepage phone-frame demo). */
export function TalentView({ talent, locale = "en", compact = false }: { talent: Talent; locale?: "en" | "es"; compact?: boolean }) {
  const c = (full: string, small: string) => compact ? small : full;
  const p = projectTalent(talent); const t = talentLabels[locale]; const tr = (value: { en: string; es: string }) => translate(value, locale);
  const contact = p.contacts.find(c => c.id === p.primaryContactId);
  const featured = p.media.find(m => m.id === p.featuredReelId);
  const recipient = (role: Talent["contacts"][number]["role"]) => role === "talent" ? t.talentRole : t[role];
  const action = contact ? <a href={contact.destination} className="inline-flex flex-col rounded-full px-7 py-3 bg-ink text-bg no-underline text-sm font-medium"><span>{tr(contact.label) || t.inquiry} ↗</span><span className="text-xs opacity-80">{recipient(contact.role)}</span></a> : null;
  const blocks: Record<string, ReactNode> = {
    reel: featured && <TalentMedia key={featured.id} item={featured} locale={locale} />,
    facts: p.facts.length > 0 && <dl className={`grid ${c("grid-cols-2 sm:grid-cols-3", "grid-cols-3")} gap-px bg-line border border-line rounded-2xl overflow-hidden`}>{p.facts.map(f => <div key={f.id} className={`bg-bg-raised ${c("p-5", "p-3 text-center")}`}><dt className={c("text-sm text-ink-soft", "text-[0.6rem] uppercase tracking-wider text-ink-soft")}>{tr(f.label) || f.key}</dt><dd className={`${c("mt-2 text-xl", "mt-1 text-sm")} font-medium break-words`}>{f.value.type === "text" ? tr(f.value.value) : f.value.type === "number" ? `${new Intl.NumberFormat(locale).format(f.value.value)} ${f.value.unit}` : f.value.value}</dd>{f.observedAt && <p className="mt-2 text-xs text-ink-soft">{t.observed} {f.observedAt}</p>}</div>)}</dl>,
    portfolio: p.media.filter(m => m.id !== p.featuredReelId).length > 0 && <div className={`grid ${c("sm:grid-cols-2", "")} gap-5`}>{p.media.filter(m => m.id !== p.featuredReelId).map(m => <TalentMedia key={m.id} item={m} locale={locale} />)}</div>,
    credits: p.credits.length > 0 && <div className="divide-y divide-line">{p.credits.map(c => <article key={c.id} className="py-5 flex flex-wrap justify-between gap-4"><div><h3 className="font-display text-xl">{tr(c.title)}</h3><p className="text-ink-soft mt-1">{[tr(c.role), c.organization].filter(Boolean).join(" · ")}</p>{c.evidenceUrl && <a className="text-sm underline" href={c.evidenceUrl} target="_blank" rel="noopener noreferrer">{t.evidence} ↗</a>}</div><span className="text-sm text-ink-soft">{c.date}</span></article>)}</div>,
    achievements: p.achievements.length > 0 && <div className={`grid ${c("sm:grid-cols-2", "")} gap-4`}>{p.achievements.map(a => <article key={a.id} className="border border-line rounded-2xl p-5"><h3 className="font-display text-xl">{tr(a.title)}</h3><p className="text-ink-soft text-sm mt-2">{[a.issuer, a.date].filter(Boolean).join(" · ")}</p>{a.evidenceUrl && <a className="text-sm underline mt-3 inline-block" href={a.evidenceUrl} target="_blank" rel="noopener noreferrer">{t.evidence} ↗</a>}</article>)}</div>,
    about: (tr(p.bio) || Object.keys(p.modules).length > 0) && <div><p className={`${c("text-lg", "text-sm")} leading-relaxed whitespace-pre-line max-w-2xl`}>{tr(p.bio)}</p><div className={`grid ${c("sm:grid-cols-2", "")} gap-6 mt-6`}>{Object.entries(p.modules).map(([key, m]) => m && <article key={key} className="border-l-2 border-gold pl-5"><h3 className="font-display text-xl mb-3">{t[key as keyof typeof p.modules]}</h3>{(["affiliation", "skills", "training", "styles", "languages", "representation"] as const).map(k => tr(m[k]) && <p key={k} className="mb-3"><span className="block text-xs uppercase tracking-wider text-ink-soft">{t[k]}</span>{tr(m[k])}</p>)}{m.sport && <p>{t.sport}: {m.sport}</p>}{m.position && <p>{t.position}: {m.position}</p>}</article>)}</div></div>,
    documents: p.documents.length > 0 && <div className="flex flex-wrap gap-4">{p.documents.map(d => <a key={d.id} href={d.url} target="_blank" rel="noopener noreferrer" className="rounded-2xl border border-line p-5 flex-1 min-w-48"><span className="block font-medium">{tr(d.title) || t[d.kind]}</span><span className="text-sm text-ink-soft">{t.download} ↗</span></a>)}</div>,
    contact: (p.contacts.length > 0 || p.links.length > 0) && <div><div className="flex flex-wrap gap-3">{p.contacts.map(c => <a key={c.id} href={c.destination} className="rounded-full border border-line-strong px-6 py-3"><span className="block text-sm font-medium">{tr(c.label) || t.inquiry} ↗</span><span className="block text-xs text-ink-soft">{recipient(c.role)}</span></a>)}</div><div className="flex flex-wrap gap-5 mt-6">{p.links.map(l => <a key={l.id} href={l.url} target="_blank" rel="noopener noreferrer" className="text-sm underline underline-offset-4">{tr(l.label) || new URL(l.url).hostname} ↗</a>)}</div></div>,
  };
  return <div data-theme={p.presentation.theme} lang={locale} className={`${c("min-h-screen", "")} bg-bg text-ink selection:bg-gold/30`}>
    <div className={`mx-auto max-w-5xl ${c("px-5 sm:px-10 py-8 sm:py-12", "px-4 pt-10 pb-6")}`}>
      <header className="flex flex-wrap justify-between gap-4 text-xs uppercase tracking-[.18em] border-b border-line pb-5"><span>SnapLink / {talentBrand(p.primaryDiscipline) ?? t.talent}</span><span>{p.sample ? t.sample : t[p.primaryGoal]}</span></header>
      <section className={`${c("py-12 sm:py-20 gap-8", "py-6 gap-5")} grid items-center ${!compact && (p.portrait || p.cover) ? "md:grid-cols-[1.1fr_1fr]" : ""}`} aria-label={t.identity}>
        <div><div className="flex flex-wrap gap-2 mb-6">{[p.primaryDiscipline, ...p.disciplines.filter(d => d !== p.primaryDiscipline)].map(d => <span key={d} className="text-xs uppercase tracking-widest rounded-full border border-line-strong px-3 py-1.5">{t[d]}</span>)}</div>
          <h1 className={`font-display ${c("text-5xl sm:text-7xl", "text-4xl")} font-medium tracking-tight leading-[1.02] break-words`}>{p.displayName}</h1><p className={`${c("text-xl sm:text-2xl mt-6", "text-base mt-3")} leading-relaxed text-ink-soft max-w-xl`}>{tr(p.headline)}</p>{p.location && <p className="text-sm text-ink-soft mt-4">{p.location}</p>}{action && <div className="mt-8">{action}</div>}
        </div>{(p.cover || p.portrait) && <div className={`relative ${compact ? "order-first" : ""}`}><img src={p.cover || p.portrait} alt={p.displayName} className="w-full aspect-[4/5] object-cover rounded-[2rem]" />{p.cover && p.portrait && <img src={p.portrait} alt={p.displayName} className="absolute bottom-5 left-5 w-24 h-24 object-cover rounded-full border-4 border-bg" />}</div>}
      </section>
      {p.presentation.sections.map(s => s.visible && blocks[s.id] ? <section key={s.id} aria-labelledby={`talent-${s.id}`} className={`border-t border-line ${c("py-9 sm:py-12", "py-6")}`}><h2 id={`talent-${s.id}`} className={`font-display ${c("text-2xl sm:text-3xl mb-6", "text-xl mb-4")} tracking-tight`}>{t[s.id]}</h2>{blocks[s.id]}</section> : null)}
      <footer className="border-t border-line pt-6 text-xs uppercase tracking-widest text-ink-soft">{talentBrand(p.primaryDiscipline) ?? t.talent} · SnapLink SOLO</footer>
    </div>
  </div>;
}
