import Link from "next/link";
import { db } from "@/db";
import { repo } from "@/db/repo";
import { registerDevice } from "./actions";
import { requireOperator } from "@/lib/operator";
export const dynamic = "force-dynamic";
export default async function DevicesPage({ searchParams }: { searchParams: Promise<{ error?: string; registered?: string }> }) {
  await requireOperator();
  const query = await searchParams;
  const devices = db ? await repo.devices.list() : [];
  return <div><div className="flex justify-between items-end mb-6"><div><p className="text-xs font-mono uppercase tracking-widest text-gold">Registry</p><h1 className="font-display text-3xl mt-2">Devices</h1></div><span className="text-xs text-ink-faint">{devices.length} registered</span></div>
    <form action={registerDevice} className="mb-6 grid gap-3 rounded-xl border border-line bg-bg-raised p-5 sm:grid-cols-2"><div className="sm:col-span-2"><p className="font-medium">Register pre-provisioned inventory</p><p className="mt-1 text-xs text-ink-faint">Registers an unclaimed physical unit. It does not assign or activate it.</p></div>{query.error && <p className="sm:col-span-2 text-sm text-err">{query.error}</p>}{query.registered && <p className="sm:col-span-2 text-sm text-ok">Device registered.</p>}<input required name="deviceCode" placeholder="Device code (12+ characters)" className="rounded-md border border-line bg-bg px-3 py-2 font-mono uppercase"/><select name="type" className="rounded-md border border-line bg-bg px-3 py-2"><option value="card">Card</option><option value="phone_plate">Phone plate</option><option value="stand">Stand</option><option value="sticker">Sticker</option><option value="bracelet">Bracelet</option><option value="keychain">Keychain</option></select><input name="label" placeholder="Label (optional)" className="rounded-md border border-line bg-bg px-3 py-2"/><input name="sku" placeholder="SKU (optional)" className="rounded-md border border-line bg-bg px-3 py-2"/><input name="hardwareProductId" placeholder="Hardware product ID (optional)" className="rounded-md border border-line bg-bg px-3 py-2"/><input name="hardwareVariantId" placeholder="Hardware variant ID (optional)" className="rounded-md border border-line bg-bg px-3 py-2"/><button className="sm:col-span-2 rounded-full bg-ink py-2.5 text-sm font-medium text-bg">Register unclaimed device</button></form>
    <div className="rounded-xl border border-line overflow-hidden"><table className="w-full text-sm"><thead className="bg-bg-sunken text-ink-faint"><tr><th className="text-left p-3">Device</th><th className="text-left p-3">Hardware</th><th className="text-left p-3">Status</th><th className="text-left p-3 hidden sm:table-cell">Activation</th></tr></thead><tbody>{devices.map((device) => <tr className="border-t border-line" key={device.id}><td className="p-3"><Link href={`/operator/devices/${device.id}`} className="font-mono text-ink no-underline hover:text-gold">{device.deviceCode}</Link></td><td className="p-3">{device.type}</td><td className="p-3 capitalize">{device.status}</td><td className="p-3 hidden sm:table-cell text-ink-faint">{device.activatedAt?.toLocaleDateString() ?? "Not activated"}</td></tr>)}</tbody></table>{!devices.length && <p className="p-8 text-center text-sm text-ink-faint">Devices appear here when assigned during fulfillment.</p>}</div>
  </div>;
}
