"use client";
import { useEffect, useRef, useState } from "react";
import type { PublicContactAction } from "@/lib/contact-channels";
import type { PublicPaymentMethod } from "@/lib/payment-methods";
import { getDict, type Locale } from "@/i18n/dict";

export function ProfileQuickActions({ username, actions, payments, locale = "en" }: { username: string; actions: PublicContactAction[]; payments: PublicPaymentMethod[]; locale?: Locale }) {
  const t = getDict(locale).contact;
  const [payOpen, setPayOpen] = useState(false); const [copied, setCopied] = useState(""); const panel = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!payOpen) return; const close = (event: KeyboardEvent) => event.key === "Escape" && setPayOpen(false); window.addEventListener("keydown", close); panel.current?.querySelector<HTMLElement>("a,button")?.focus(); return () => window.removeEventListener("keydown", close); }, [payOpen]);
  const quick = actions.filter((action) => action.type !== "share" && action.type !== "vcard" && action.type !== "custom").slice(0, payments.length ? 2 : 3);
  if (!quick.length && !payments.length) return null;
  const track = (event: string) => { void fetch("/api/profile-event", { method: "POST", headers: { "Content-Type": "application/json" }, keepalive: true, body: JSON.stringify({ username, event }) }); };
  async function guardian(action: PublicContactAction) { const response = await fetch("/api/kids/reveal", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username, priority: 1 }) }); if (!response.ok) return; const result = await response.json() as { phone?: string }; if (!result.phone) return; const digits = result.phone.replace(/\D/g, ""); window.location.href = action.type === "call" ? `tel:${result.phone}` : action.type === "sms" ? `sms:${result.phone}` : `https://wa.me/${digits}`; }
  return <div className="mt-5 flex items-start justify-center gap-3" aria-label={t.quickActions}>
    {quick.map((action) => action.guardian ? <button key={action.type} onClick={() => void guardian(action)} className="group grid min-w-14 place-items-center gap-1 text-center text-[0.65rem] text-ink-soft"><span className="grid h-11 w-11 place-items-center rounded-full border border-line-strong bg-bg-raised group-hover:border-gold"><ActionGlyph type={action.type}/></span>{action.label}</button> : <a key={action.type} href={action.href ?? "#"} onClick={() => track(`${action.type}_clicked`)} className="group grid min-w-14 place-items-center gap-1 text-center text-[0.65rem] text-ink-soft no-underline"><span className="grid h-11 w-11 place-items-center rounded-full border border-line-strong bg-bg-raised group-hover:border-gold"><ActionGlyph type={action.type}/></span>{action.label}</a>)}
    {payments.length > 0 && <button onClick={() => { setPayOpen(true); track("pay_opened"); }} className="group grid min-w-14 place-items-center gap-1 text-center text-[0.65rem] text-ink-soft"><span className="grid h-11 w-11 place-items-center rounded-full border border-line-strong bg-bg-raised group-hover:border-gold"><ActionGlyph type="pay"/></span>{t.payTip}</button>}
    {payOpen && <div className="fixed inset-0 z-50 bg-black/20" onMouseDown={(event) => event.target === event.currentTarget && setPayOpen(false)}><div ref={panel} role="dialog" aria-modal="true" aria-label={t.payOrTip} className="absolute inset-x-4 mx-auto max-w-sm rounded-2xl border border-line bg-bg-raised p-3 shadow-xl" style={{ bottom: "max(5rem, calc(env(safe-area-inset-bottom) + 4.5rem))" }}><div className="flex min-h-11 items-center justify-between px-2"><div><p className="font-display text-lg font-medium">{t.payTip}</p><p className="text-[0.65rem] text-ink-faint">{t.choosePayment}</p></div><button onClick={() => setPayOpen(false)} aria-label={t.closePayments} className="h-11 w-11 rounded-full hover:bg-bg-sunken">×</button></div><div className="grid gap-1 mt-1">{payments.map((method) => method.href ? <a key={method.type} href={method.href} target="_blank" rel="noopener noreferrer" onClick={() => track("payment_method_clicked")} className="flex min-h-11 items-center justify-between rounded-xl px-4 text-sm font-medium text-ink no-underline hover:bg-bg-sunken"><span>{method.displayLabel}</span><span aria-hidden="true">↗</span></a> : <button key={method.type} onClick={async () => { if (!method.copyValue) return; await navigator.clipboard?.writeText(method.copyValue); setCopied(method.type); track("payment_method_clicked"); }} className="flex min-h-11 items-center justify-between rounded-xl px-4 text-left text-sm font-medium hover:bg-bg-sunken"><span>{method.displayLabel}</span><span className="text-xs text-ink-faint">{copied === method.type ? t.copied : t.copy}</span></button>)}</div></div></div>}
  </div>;
}

function ActionGlyph({ type }: { type: string }) { return <svg aria-hidden="true" viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{type === "call" ? <path d="M7 3 4.5 5.5c.8 6.5 5.5 11.2 12 12L19 15l-4-2-1.5 2c-2.2-.9-3.6-2.3-4.5-4.5L11 9 9 5Z"/> : type === "sms" ? <path d="M4 5h16v11H9l-5 4Z"/> : type === "email" ? <><path d="M3 5h18v14H3Z"/><path d="m3 6 9 7 9-7"/></> : type === "pay" ? <><rect x="3" y="6" width="18" height="12" rx="2"/><path d="M3 10h18M16 14h2"/></> : <><circle cx="12" cy="12" r="8"/><path d="M8.5 12h7"/></>}</svg>; }
